--- #YAML:1.0
name:               Net-Amazon-ATS
version:            0.03
abstract:           Use the Amazon Alexa Top Sites Service
author:
    - Shevek <cpan@anarres.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Prompt:       0
    Test::Exception:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
